### ISSUE TITLE
Maya VRay - Module install not working properly

### ISSUE THREAD

**Issue by gamlon** [zicher3d-org/domemaster-stereo-shader#12]
Having VRay as a serperate module loaded in Maya does result in not being able to have these functions:

https://github.com/zicher3d-org/domemaster-stereo-shader/wiki/Vray-for-Maya-Domemaster3D#vray-domemasterstereo-camera

as these files 

https://github.com/zicher3d-org/domemaster-stereo-shader/tree/master/Domemaster3D%20Installer/installer%20files/Domemaster3D/vray/install/maya/vray%203.10%20for%20Maya/vray%20scripts

are not being used.

**Comment by AndrewHazelden** [comment]
Hi Gamion.

Oh, those vray script files do work... The issue is just that they have to be installed by physically overwriting those same files in the actual VRay installation folder. 

And before you ask, yes, that is just how Vray for Maya was programmed to work with custom shaders and not something that a 3rd party lens shader installation can do any other way that I am aware of. 

Vray won't load any of these customized files if you simply have them copied to your personal Maya scripts folder:

- attributes.txt
- attributeNodes.txt
- attributeGroups.txt
- vrayAEFunctions.mel
- domeVrayRender.py

It is covered in step 5 of the [Vray for Maya Domemaster "Maya Shader Installation"](https://github.com/zicher3d-org/domemaster-stereo-shader/wiki/Vray-for-Maya-Domemaster3D#maya-shader-installation) section:

**Step 5.** Copy the Vray script files from `C:\Program Files\Domemaster3D\vray\install\maya\vray <Vray Version> for Maya\vray scripts\` to the Vray scripts folder:  

`C:\Program Files\Autodesk\Maya<Version>\vray\scripts\`

Vray Script Files:

    attributes.txt
    attributeNodes.txt
    attributeGroups.txt
    vrayAEFunctions.mel
    domeVrayRender.py

**Note:** Several of the Vray script files listed above already exist in the standard Vray install. Those items need to be replaced with new ones that have the DomemasterStereo and LatLongStereo modules integrated in the settings. You should make a backup copy of the original files so you can restore them if required.

**Comment by gamlon** [comment]
Hi Andrew,

this was what I was doing. I was hoping there is a way to add to VRays extra attributes so we can have any plugin as a module aside from Maya`s main installation and add on top of Vray`s functionality. The current way does require the patch per VRay version. 

I send a request to Chaosgroup to see if they have a way to patch in new extra attributes on the fly.

Thanks for the fast reply!

**Comment by gamlon** [comment]
Hi Andrew,

FYI - I got this from Chaosgroup.

Hello Daniel,

We are planing to extend the API for third partly plugins from the next
major version of the software.
That change will help other developers to develop and maintain their
plugins in a much better way.

If you need any further assistance, please reply to this email.

Thank you,
Chaos Group Support

**Comment by AndrewHazelden** [comment]
Hi Daniel. Thanks for the information update. It is nice to hear that. 😀
