### ISSUE TITLE
Maya 3D-Lat FOV/Focal Length

### ISSUE THREAD

**Issue by KyleJSmith1** [zicher3d-org/domemaster-stereo-shader#13]
Hey Andrew, zicher3d, or anyone willing to assist,

Domemaster is really something. Good work. But I hope I can ask some of your time to help me with an issue I'm having with it.

I'm rendering with the Latitude-Longitude Stereo camera. The scene is an average-sized room, and the goal is to get a 360 video. It works, but when viewing through a 360 video player, everything is distorted with a fish eye effect, making the room seem to have the size of an airplane hangar. I understand some distortion might be expected, but my renders have much more distortion than I've seen 360 videos to have (and I have tested comparisons using the same player). 

As a Maya user, my first instinct was to change the Focal Length, but that is of no use. It resets upon rendering. I've looked over much of your documentation that talks about this field being controlled by a script. But even when going into the mel scripts, such as domeRender.mel, I'm at a loss of what to change, and anything I try has no effect.

I've also tried modifying the stereo nodes' horizontal and vertical field of view fields, but that just makes it no longer a 360 video. Much of the documentation and scripts speak of a DomeAFL_FOV node, but that node doesn't seem to appear within the hierarchy of the Latitude-Longitude Stereo camera structure.

Those are things I've tried. Am I missing something? I sincerely hope that there is indeed a way to reduce the fish eye effect within a 360 video render sequence. If so, could you tell me how I might accomplish this with the use of Domemaster?

Thank you

**Comment by AndrewHazelden** [comment]
Hi KyleJSmith1.

Are you rendering with mental ray or Arnold? The mental ray version of Domemaster3D for Maya is feature complete, while the Arnold version is still a beta release that is lacking the stereoscopic screen space control texture map features.

Can you attach a scaled down image of your rendering so I can see what type of distortion you are describing?

**Comment by AndrewHazelden** [comment]
Hi @KyleJSmith1 . Are you viewing your renderings in Go Pro VR Player or Kolor Eyes? Both of those panoramic media viewers allow you to do a "tiny planet" image projection like zooming effect on a panoramic image by rolling your scroll wheel on your mouse.

**Comment by KyleJSmith1** [comment]
Thanks for replying! I'm using Maya 2015, so I'm using Mental Ray. I'm sorry for not mentioning that. 

I'm using VLC's 360 player, but yes it has said scrolling effect. I'm not sure that is ideal however, as it essentially crops the view. I'd like to get less distortion without getting tunnel vision.

Unfortunately, I am not allowed to show any images of this scene. But I have a solution. I blocked up the scene, and hopefully it'll be enough for you to see the distortion in effect.

![test4](https://cloud.githubusercontent.com/assets/25374926/22353700/bed5dd9a-e3ef-11e6-9963-007870803c1b.jpg)
![test4_1](https://cloud.githubusercontent.com/assets/25374926/22353702/bed8be3e-e3ef-11e6-86b4-3327c9b32b14.JPG)
![test4_2](https://cloud.githubusercontent.com/assets/25374926/22353699/bed5d99e-e3ef-11e6-8582-bf698602d8c0.JPG)
![test4_3](https://cloud.githubusercontent.com/assets/25374926/22353703/bed90182-e3ef-11e6-8299-72cb0fde53d0.JPG)
![test4_4](https://cloud.githubusercontent.com/assets/25374926/22353701/bed748f6-e3ef-11e6-8d45-03331e8fb8e5.JPG)

Image 0 (test4) shows the render itself. The additional images show views in the 360 player. In images 1-3, look at the block-person on the left and perhaps the opposing end of the room on the right. The apparent distance between us and the block person shrinks while the distance between us and the opposing end grows. Fish-eye.

Is there a way to reduce this? Can I reduce the focal length? The field of view? And can I do any of these whilst still being able to be used as a 360 video?

**Comment by AndrewHazelden** [comment]
Hi. If you are targeting your output for an HMD (head mounted display) or for a site like YouTube 360, then your only output setting needed for the field of view would be to create a LatLong image with a 360x180 degree field of view.

Have you actually used a Google Cardboard, or an Oculus Rift/HTC Vive to view panoramic content?

If you want to change the viewing experience in a panorama that is by moving the camera closer or farther from an object. You don't mess with the FOV setting in a LatLong rendering as it is always a 360x180° output.

I have to comment as a side note, that your fixation with zooming the FOV on the image in your panoramic viewing program is more of a desktop PC user playing with a panoramic viewer program for the first time on a computer monitor than something that an HMD user or a YouTube 360 user would ever do since in a VR program on an HMD you would typically have the FOV setting locked into a human eye native FOV value that is specific to the display screen.

Anything other than that default setting on your panoramic viewer program is switching things up  for artistic purposes and is equal to viewing your output as a "tiny planet" image projection which makes things "cartooney". 

The swirl pattern on the ground in your rendering is likely caused by your world scale not being set to real world units in Maya. In a panoramic 3D rendering the stereo depth in the left and right eye views is pushed from the lens shader's standard stereo 3D depth value to mono 2D at the zenith and nadir pole zones using the stereo separation map controls on the lens shader.

If you adjust the zero parallax distance setting and the camera separation control you can refine and tune the stereo effect in the scene and the "swirl" pattern will go away.

Read over these Wiki posts for details on how to tune a panoramic lens shader's stereo settings:

https://github.com/zicher3d-org/domemaster-stereo-shader/wiki/Maya-LatLong_Stereo

https://github.com/zicher3d-org/domemaster-stereo-shader/wiki/Maya-DomeAFL_FOV_Stereo#cameras-separation

https://github.com/zicher3d-org/domemaster-stereo-shader/wiki/Maya-DomeAFL_FOV_Stereo#working-in-3d

The cropped field of view settings on the lens shaders are only really used by people who are making custom theater screens for ride films, or for doing video projection mapping.

**Comment by AndrewHazelden** [comment]
If you are just getting started with 360 video production and CG panoramic rendering as a whole, you might check to see if a friend has a Ricoh Theta or a Samsung Gear 360 camera. 

Playing with real world panoramic photos you have taken in a location you are familiar with like your home is the fastest way to understand camera framing and panoramic view perspectives in 360° media that are equally relevant to live action 360° media and panoramic computer renderings.

**Comment by AndrewHazelden** [comment]
To reduce the stereoscopic "swirl" artifact in the ground "nadir" pole zone in the LatLong stereo panorama, you might try this quick adjustment:

Use Maya's distance measurement tool to check how far it is in the top view from the camera to your "box person" on by the far wall. Enter that distance value as the Zero Parallax Distance in the "Center_LatLong_Stereo" named lens shader node in the Attribute Editor which is used to control the stereoscopic camera rig's center camera. 

Then take your Zero Parallax Distance and divide it by 120 and enter this resulting number in the Camera Separation attribute in the lens shader. This should get the stereoscopic effect to be in the rough "ballpark zone" that is comfortable for the viewer regardless of what scene unit size you modeled your Maya project using.

**Comment by KyleJSmith1** [comment]
Thank you for the reply, Andrew.

I hadn't tried using an HMD, but I recently acquired one (Oculus). But I understand now, the concept I had of the focal length for the 360 video was flawed. Changing it is not only not possible, but not advisable. The "fish-eye" doesn't look so bad when wearing the HMD. I'll keep the scrolling/zooming in mind if a scene does continue to bother me.

Thank for the tips regarding zero parallax distance for the swirl. It worked, and I managed to get the swirl to go away.

Sorry for taking so much of your time and for my own confusion. I really appreciate your responsiveness! You can go ahead and mark this issue as resolved.
